### ISSUE TITLE
Tag the repository

### ISSUE THREAD

**Issue by chriseidhof** [ddeville/DDPageControl#3]
Hey Damien,

I wanted to add DDPageControl to [CocoaPods](http://cocoapods.org/), so people can use it even more easily in their own projects. However, it would be very helpful for me if you could tag the current branch with a version number, e.g. "0.1". That way we can create a pod file that will always work.

Thanks,
Chris

**Comment by ddeville** [comment]
Just done it!

I've also tagged [DDProgressView](https://github.com/ddeville/DDProgressView) in case that's helpful ;)

**Comment by chriseidhof** [comment]
Awesome, thanks. I just added it to the specs:
https://github.com/CocoaPods/Specs/commit/711cfe6dd1ffa0583a31053156f92c62de992780

Feel free to create a spec file for DDProgressView, it's really simple!

Chris

On Wed, Mar 14, 2012 at 11:24 AM, Damien DeVille <
reply@reply.github.com

> wrote:
> 
> Just done it!
> 
> I've also tagged [DDProgressView](https://github.com/ddeville/DDProgressView) in case that's helpful ;)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ddeville/DDPageControl/issues/3#issuecomment-4495551

## 

Chris Eidhof

**Comment by ddeville** [comment]
Cool, thanks, will do!
